# Generated by Django 4.0.4 on 2022-05-14 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Osztaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evfolyam', models.CharField(choices=[('NY', 'NY'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2)),
                ('tagozat', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2)),
            ],
            options={
                'verbose_name': 'Osztály',
                'verbose_name_plural': 'Osztályok',
            },
        ),
        migrations.CreateModel(
            name='Tanulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255)),
                ('osztaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jelenletiv.osztaly')),
            ],
            options={
                'verbose_name': 'Tanuló',
                'verbose_name_plural': 'Tanulók',
            },
        ),
        migrations.CreateModel(
            name='Foglalkozas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('diakok', models.ManyToManyField(to='jelenletiv.tanulo')),
                ('edzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foglalkozás',
                'verbose_name_plural': 'Foglalkozások',
            },
        ),
        migrations.CreateModel(
            name='Alkalom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('foglalkozas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jelenletiv.foglalkozas')),
                ('resztvett', models.ManyToManyField(to='jelenletiv.tanulo')),
            ],
            options={
                'verbose_name': 'Alkalom',
                'verbose_name_plural': 'Alkalmak',
            },
        ),
    ]
