# Generated by Django 4.0.4 on 2022-05-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jelenletiv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alkalom',
            name='resztvett',
            field=models.ManyToManyField(blank=True, to='jelenletiv.tanulo'),
        ),
    ]
