# Generated by Django 3.2.13 on 2022-05-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jelenletiv', '0003_rename_resztvett_alkalom_hianyzok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osztaly',
            name='evfolyam',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='osztaly',
            name='tagozat',
            field=models.CharField(max_length=1),
        ),
    ]
